# Generated by Django 4.2 on 2025-05-14 07:17

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arabic_name', models.CharField(db_index=True, max_length=100)),
                ('english_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['english_name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arabic_name', models.CharField(db_index=True, max_length=100)),
                ('english_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['english_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arabic_name', models.CharField(db_index=True, max_length=200)),
                ('english_name', models.CharField(db_index=True, max_length=200)),
                ('brand_in_arabic', models.CharField(max_length=100)),
                ('brand_in_english', models.CharField(max_length=100)),
                ('nutrition_facts', models.JSONField(blank=True, default=dict)),
                ('name_translit', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('keywords', models.ManyToManyField(blank=True, related_name='products', to='products.keyword')),
            ],
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_name'], name='keyword_arabic_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['english_name'], name='keyword_english_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_name'], name='cat_arabic_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['english_name'], name='cat_english_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_name'], name='prod_arabic_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['english_name'], name='prod_english_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_translit'], name='prod_name_translit_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
