# Generated by Django 4.2 on 2025-05-16 09:05

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_translit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='keyword',
            name='name_translit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_translit'], name='cat_translit_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_translit'], name='keyword_translit_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
