# Generated by Django 4.2 on 2025-05-16 09:18

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_name_translit_keyword_name_translit_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='keyword',
            new_name='ky_arabic_name_gin_idx',
            old_name='keyword_arabic_name_gin_idx',
        ),
        migrations.RenameIndex(
            model_name='keyword',
            new_name='ky_english_name_gin_idx',
            old_name='keyword_english_name_gin_idx',
        ),
        migrations.RenameIndex(
            model_name='keyword',
            new_name='ky_translit_gin_idx',
            old_name='keyword_translit_gin_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='arabic_translit',
            field=models.CharField(blank=True, help_text='English to Arabic transliteration', max_length=100),
        ),
        migrations.AddField(
            model_name='keyword',
            name='arabic_translit',
            field=models.CharField(blank=True, help_text='English to Arabic transliteration', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='arabic_translit',
            field=models.CharField(blank=True, help_text='English to Arabic transliteration', max_length=200),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_translit'], name='cat_arabic_translit_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_translit'], name='ky_arabic_translit_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_translit'], name='prod_arabic_translit_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
