# Generated by Django 4.2 on 2025-05-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_keyword_arabic_name_gin_idx_ky_arabic_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='keyword',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['version'], name='cat_version_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['version'], name='ky_version_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['version'], name='prod_version_idx'),
        ),
    ]
