# Generated by Django 4.2 on 2025-05-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_version_keyword_version_product_version_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brand',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['english_name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='brand',
        ),
    ]
