# Generated by Django 4.2 on 2025-05-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_category_brand_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_in_arabic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_in_english',
        ),
    ]
